"""Typed, read-only Robot Knowledge Base evidence models."""

from .alerts import AlertSeverity, RKBAlert, evaluate_alerts
from .canonical import (
    canonical_json,
    json_pointer,
    payload_digest,
    pointer_for_fact,
    resolve_json_pointer,
)
from .collector import SnapshotCollector, collect_snapshot
from .episodes import (
    EpisodeArtifactRef,
    EpisodeEvent,
    EpisodeEventKind,
    EpisodeMetadata,
    EpisodeMetrics,
    EpisodeQueryPage,
    EpisodeState,
    EpisodeStore,
    build_episode_from_snapshot,
    build_terminal_episode,
    publish_probe_episode,
)
from .keyring import HMACKey, HMACKeyring
from .migration import (
    bundle_to_snapshot,
    probe_to_snapshot,
    snapshot_to_discovery_report,
    snapshot_to_legacy_probes,
    verified_bundle_to_snapshot,
)
from .models import (
    EvidenceEnvelope,
    Fact,
    FactConfidence,
    FactSourceKind,
    FreshnessStatus,
    IdentityStatus,
    Snapshot,
    SnapshotIdentity,
    envelope_from_probe,
    snapshot_from_target_bundle,
)
from .query import QueryRejectedError, QueryResult, ReadOnlyKnowledgeBase, SnapshotReference
from .read_models import (
    CapabilityRecord,
    CapabilityState,
    ExecutableModel,
    HardwareInventoryModel,
    HardwareResourceModel,
    MiddlewareEndpointModel,
    MiddlewareGraphModel,
    MiddlewareRelationshipModel,
    ReadModelMetadata,
    RobotIdentityModel,
    RuntimeStatusModel,
    Stability,
    StateSafetyModel,
    TypedQueryResult,
    UnknownValue,
)
from .scheduler import AlertSchedule, run_alert_cycle
from .schema_registry import SchemaPolicy, SchemaRegistry
from .storage import RKBMetrics, RKBStore
from .validation import (
    EvidenceValidationError,
    freshness_status,
    validate_bundle_hmac,
    validate_envelope,
    validate_fact,
    validate_identity,
    validate_snapshot,
)
from .vault import keyring_from_vault

__all__ = [
    "EvidenceEnvelope",
    "Fact",
    "FactConfidence",
    "FactSourceKind",
    "FreshnessStatus",
    "IdentityStatus",
    "SnapshotIdentity",
    "Snapshot",
    "canonical_json",
    "envelope_from_probe",
    "snapshot_from_target_bundle",
    "QueryResult",
    "TypedQueryResult",
    "UnknownValue",
    "SnapshotReference",
    "QueryRejectedError",
    "ReadOnlyKnowledgeBase",
    "ReadModelMetadata",
    "RobotIdentityModel",
    "RuntimeStatusModel",
    "HardwareResourceModel",
    "HardwareInventoryModel",
    "MiddlewareEndpointModel",
    "MiddlewareRelationshipModel",
    "MiddlewareGraphModel",
    "ExecutableModel",
    "CapabilityRecord",
    "CapabilityState",
    "StateSafetyModel",
    "Stability",
    "payload_digest",
    "json_pointer",
    "resolve_json_pointer",
    "pointer_for_fact",
    "bundle_to_snapshot",
    "probe_to_snapshot",
    "snapshot_to_legacy_probes",
    "snapshot_to_discovery_report",
    "verified_bundle_to_snapshot",
    "EvidenceValidationError",
    "validate_identity",
    "validate_fact",
    "validate_envelope",
    "validate_snapshot",
    "validate_bundle_hmac",
    "freshness_status",
    "RKBMetrics",
    "RKBStore",
    "SnapshotCollector",
    "collect_snapshot",
    "AlertSeverity",
    "RKBAlert",
    "evaluate_alerts",
    "HMACKey",
    "HMACKeyring",
    "SchemaPolicy",
    "SchemaRegistry",
    "AlertSchedule",
    "run_alert_cycle",
    "keyring_from_vault",
    "EpisodeArtifactRef",
    "EpisodeEvent",
    "EpisodeEventKind",
    "EpisodeMetrics",
    "EpisodeMetadata",
    "EpisodeQueryPage",
    "EpisodeState",
    "EpisodeStore",
    "build_episode_from_snapshot",
    "build_terminal_episode",
    "publish_probe_episode",
]
